# Generated by Django 4.2.4 on 2023-08-18 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banking',
            name='price',
        ),
    ]
